### PR TITLE
Handle multiple guards.

### LINKED ISSUE #488: Multiple Guards on a Single Route
- Laravel Version: 6.8
- Laratrust Version: 5.2.9

**Describe the bug**
Laravel handles this auth statement just fine, such that 3 user types, each with their own guards can share a single route.  If any of the three guards allow access, then access to the route is allowed:
        Route::middleware([
            'auth:api,client,its'
        ])->group(function () {
            Route::get('/stuff', 'StuffController@all');
        });

Unfortunately, when I try to add a Laratrust permission check, only the first guard that I list is checked:
        Route::middleware([
            'auth:api,client,its',
            'permission:' . Permission::READ_ASSET . ",guard:api|guard:client|guard:its"
        ])->group(function () {
            Route::get('/stuff', 'StuffController@all');
        });

This seems to be an explicit assumption of LaratrustMiddleware::extractGuard(), as it uses ->first() during the extraction:
    protected function extractGuard($string)
    {
        $options = Collection::make(explode('|', $string));

        return $options->reject(function ($option) {
            return strpos($option, 'guard:') === false;
        })->map(function ($option) {
            return explode(':', $option)[1];
        })->first();
    }

**To Reproduce**
See above.

**Question**
Is there some way to manage multiple guards on the same route?

### PR DESCRIPTION
**Pull request by derekrprice**
Fixes #488.

### CODE REVIEW

**Comment by santigarcor** [comment]
@derekrprice Can we make it to work like this: `permission:edit-post|edit-user,guard:api|web` so we don't have to put `guard:` multiple times?

**Comment by derekrprice** [comment]
The parsing would be easy enough, but how do you want me to make that work with the "require_all" flag?  That is [documented here](https://laratrust.santigarcor.me/docs/6.x/usage/middleware.html#using-different-guards) as being separated from "guard:" specs by a pipe.  Can I assume that require_all will always come first?  If it appears like this, "guard:api|its|require_all", the syntax you suggested will interpret "require_all" as a guard, and that might be a breaking change for existing implementations.

**Comment by santigarcor** [comment]
I think that one is separated by the comma as you can see here: `role:admin|root,my-awesome-team,require_all` so in theory we wouldn't need to monkey with it.

**Comment by derekrprice** [comment]
I was worried about this one: `'ability:admin|owner,create-post|edit-user,require_all|guard:web`.  Looking at the current parser, commas between require_all and guard: would have worked fine, but anyone working off this doc and using a pipe may end up surprised.

**Comment by derekrprice** [comment]
I made this change locally and, in fact, you have several tests that use the `guard:api|require_all` syntax already.  The first one that fails is `Laratrust\Tests\Middleware\LaratrustPermissionTest::testHandle_IsLoggedInWithNoPermission_ShouldAbort403`, but there are several others as well.  After fixing the two tests I added to use commas to separate require_all from guard: with a comma, 7 tests fail with messages like this:

    7) Laratrust\Tests\Middleware\MiddlewareLaratrustAbilityTest::testHandle_IsLoggedInWithNoAbility_ShouldAbort403
    Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_4_Illuminate_Auth_AuthManager::guard('require_all'). Either the method was unexpected or its arguments matched no expected argument list for this method
    
    /home/derek/Code/laratrust/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:92
    /home/derek/Code/laratrust/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
    /home/derek/Code/laratrust/src/Middleware/LaratrustAbility.php:35
    /home/derek/Code/laratrust/tests/Middleware/MiddlewareLaratrustAbilityTest.php:93

**Comment by derekrprice** [comment]
I suppose that I could just add a special case to the parser and assume that require_all isn't a guard regardless of where it appears, for backwards compatibility.  Is that what you want me to do?

**Comment by derekrprice** [comment]
Done.  Any of these syntaxes work correctly now:

    require_all|guard:api|web
    guard:api|web|require_all
    require_all,guard:api|web
    guard:api|web,require_all

Also should be resilient to stupid mistakes like the following, (silently) falling back on the default guard in all cases:

    require_all,guard:
    guard:|
    guard:require_all

**Comment by santigarcor** [comment]
Sorry @derekrprice I think your first option was the best one. Because  the third set after the second comma are the extra options for the middleware so it's better to repeat `guard:...`  multiple times in that third set of arguments

**Comment by derekrprice** [comment]
Shoot.  I force-pushed the change.  Is there a way to revert a single commit after an `git commit --amend` followed by a force push?  Would like to avoid re-implementing.

**Comment by santigarcor** [comment]
Maybe you can close the PR, delete the remote branch and in your local revert to the previous commit and then push it again and open the PR again

**Comment by derekrprice** [comment]
I the `commit --amend` overwrite the original commit.  I'll figure something out.

**Comment by derekrprice** [comment]
There you go.  Didn't have to redo too much.

**Comment by derekrprice** [comment]
This has been outstanding a long time.  I still like the syntax, but I don't think my implementation was correct.  This allowed the multiple guards but would sometimes find the wrong user when there was an ID overlap.  In any case, I'm no longer working with the code that I needed this for, so I am just going to close this PR.

**Pull request closed without merging**
