### PR TITLE
Fix for issue #57

### PR DESCRIPTION
**Pull request by stevevg**
Maybe quick and dirty, but it works in my case to fix issue #57

### CODE REVIEW

**Comment by santigarcor** [comment]
@stevevg i don't understand why are you unsetting the roles `relations` attribute if the problem is with the whole user being saved to the cache.

**Comment by stevevg** [comment]
Because the problem is that, in addition to roles, the command `$this->roles()->get();` saves into cache (as relation of the role) also the user and all of its relations.
By unsetting the roles `relations`, I am able to delete the user and all subsequent relations.

**Comment by santigarcor** [comment]
But why your roles are bringing the user, did you add something to the role model? because normally it does not bring the relationships.

**Comment by stevevg** [comment]
Actually I added the permissions() and users() belongsToMany relationships to the model (I thought I needed these in order for the component to work correctly and to be able to manage all the CRUD operations on roles, users and permissions...)

**Pull request merged**
