### PR TITLE
Create teams function and update doc

### PR DESCRIPTION
**Pull request by ralbear**
With this function you can retrieve all teams for a given user. Also update the doc.

### CODE REVIEW

**Comment by ralbear** [comment]
Hey @santigarcor have you find interesting this function? did you have planned merge it? Thanks! :)

**Comment by santigarcor** [comment]
Yes, I'll merge it to a new release, because it could cause problems with people code.

**Comment by ralbear** [comment]
Sounds great!, thanks :)

**Comment by santigarcor** [comment]
@TechyChameleon I've been a bit busy that's why I haven't released this new version but i hope to release it before new year.

**Comment by TechyChameleon** [comment]
No worries man!

Relieved that's the issue and not me doing something wrong :)

Cheers

**Comment by maks112v** [comment]
Has it been released yet?

**Comment by santigarcor** [comment]
@maks112v I'm planning on doing it between this week and next one.

**Comment by marabesi** [comment]
@santigarcor any update on that? I just started to use laratrust but couldn't find the method in the LaratraitUserTrait

**Comment by santigarcor** [comment]
@marabesi I renamed the relationship to `rolesTeams()` but it's [there](https://github.com/santigarcor/laratrust/blob/master/src/Traits/LaratrustUserTrait.php#L82) in the 5.1 release.

**Pull request merged**
