### PR TITLE
Master

### PR DESCRIPTION
**Pull request by prekoc**
issue #38

### CODE REVIEW

**Comment by hamdallah90** [comment]
When can you start using this?

**Comment by santigarcor** [comment]
@hamdallah90 I'm finishing my university, so in a few weeks maybe 2.

**Comment by KKSzymanowski** [comment]
@santigarcor Where do you study, if I may ask?

**Comment by santigarcor** [comment]
@KKSzymanowski It's called Universidad EIA (http://www.eia.edu.co/)

**Comment by hamdallah90** [comment]
ok thanks :). please, i want this changes ASAP. can I help you with it?

**Comment by santigarcor** [comment]
@hamdallah90 i'll try to make something this weekend.

**Comment by santigarcor** [comment]
@hamdallah90 You can use it by requiring the `dev-master` branch

**Comment by hamdallah90** [comment]
Thanks :)

**Pull request merged**
