### PR TITLE
Added optional hierarchical LaratrustHasLevelsTrait

### PR DESCRIPTION
**Pull request by timramseyjr**
Added optional  hierarchical trait

### CODE REVIEW

**Comment by santigarcor** [comment]
Thank you man i'll review it as soon as i'm back. But in the mean time can you please solve the tests problems and also write some tests for it?

**Comment by timramseyjr** [comment]
Yeah, it will probably be later this week before I can devote the time for the test.  I will rename it to levels in the docs, but the entire concept is to allow you to add a type of hierarchy to roles via leveling.

**Comment by KKSzymanowski** [comment]
At a glance it looks like this feature can be separate from Laratrust(correct me if I'm wrong).
As far as I know it's not a very common requirement to have these levels and in my opinion it would be better to keep it separate(keeping Laratrust focused on the core authorization idea).
Once you finish this package, @santigarcor can add a link in the Readme/docs and add a suggestion displayed after composer installation, so that everyone who needs it can easily find it.

**Comment by timramseyjr** [comment]
I specifically asked in the Issues/Question if @santigarcor wanted a PR for this functionality.  If you do not want this functionality please just close PR and issue/question as it would have been a waste of time to go through all the work of writing migrations/Traits/etc and separating everything out as I have already coded what I needed a while ago.

**Pull request closed without merging**
