### PR TITLE
Multiple fixes from old pull requests

### PR DESCRIPTION
**Pull request by filippotoso**
Multiple fixes from old pull requests.

### CODE REVIEW

**Comment by KKSzymanowski** [comment]
I'd revert the formatting changes from this commit: https://github.com/santigarcor/laratrust/pull/587/commits/135253127e0bcb5adcef7ee83187a5bf593f4720

**Comment by santigarcor** [comment]
Yeah, i agree with Kuba, just revert those changes on the formating

**Comment by filippotoso** [comment]
> Yeah, i agree with Kuba, just revert those changes on the formating

Sorry, I forgot to disable VSC autoformatting.

**Comment by KKSzymanowski** [comment]
Looks good to me know

**Pull request merged**
