### PR TITLE
Register permissions to Laravel Gate

### PR DESCRIPTION
**Pull request by denisdulici**
This will allow us to use all functionalities of [Gates](https://laravel.com/docs/authorization#gates), including `$user->can('permission-name')` or `@can('permission-name')` blade directive.

### CODE REVIEW

**Comment by denisdulici** [comment]
@santigarcor Any change to take a look at this?

**Comment by santigarcor** [comment]
@denisdulici that's a nice one, is there any way to make a test for this?

**Comment by denisdulici** [comment]
Just added tests 😉

**Comment by santigarcor** [comment]
Would this break people's code if they had a gate already defined and are using Laratrust?

**Comment by denisdulici** [comment]
Nope, it will just work perfectly.

**Comment by santigarcor** [comment]
Thank you! You can use dev-master for now until I do the actual release. BTW If you want to add another PR to update the docs I'll be grateful :smile:

**Comment by Tofandel** [comment]
I was wondering why was this feature removed in the first place in 6.x, glad it's back..

**Comment by gdebrauwer** [comment]
@santigarcor This does break existing projects that have a gate defined with the same name as a laratrust permission.
I think this feature should only be enabled if explicitly requested in the laratrust config

**Pull request merged**
