### PR TITLE
ability to put laratrust panel in subdomain

### PR DESCRIPTION
**Pull request by hamoda-dev**
Hi @santigarcor 
I found this issue: [Sub Domain Route](https://github.com/santigarcor/laratrust/issues/556)
I open this pull request to add this feature, can you review it

### CODE REVIEW

**Comment by ahr1384** [comment]
Can I use this for another domain? are you test it?

**Comment by ahr1384** [comment]
Can I use this for another domain? are you test it? @hamoda-dev

**Comment by hamoda-dev** [comment]
@ahr1384 
yes, you can use it.
just specify the domain by add 
LARATRUST_PANEL_DOMAIN
to dot env file
if your primary domain is example.com and you need to put the panel in a subdomain called laratrust

LARATRUST_PANEL_DOMAIN=laratrust.example.com
or edit the laratrust config file ```panel.domain```
the route will be ```laratrust.example.com/laratrust``` if you need to add it to the root of the subdomain
update laratrust config file ```panel.path```  from ```laratrust``` to ```/```

@santigarcor add this to the docs when you merge
ـ

**Comment by ahr1384** [comment]
Tanks @hamoda-dev

**Comment by ahr1384** [comment]
@santigarcor

**Comment by filippotoso** [comment]
Thanks for the PR. I'm going to close it because to add this feature some fallback logic must be implemented. This feature will be added in the next release.

**Pull request closed without merging**
