### PR TITLE
Add new params to LaratrustMiddleware for redirects

### PR DESCRIPTION
**Pull request by m1kfb**
Allow people the option to flash error messages when the middleware redirects them.

### CODE REVIEW

**Comment by santigarcor** [comment]
I like the idea, but the configuration file would be better like this:
```php
'middleware' => [
    'register' => true,
    'handling' => 'abort',
    'handlers' => [
        'abort' => [
            'code' => 403
        ],
        'redirect' => [
            'url' => '/home',
            'message' => [
                'type' => 'error',
                'content' => ''
            ]
        ]
    ]
],
```

Also, could you please add tests for this.

**Comment by m1kfb** [comment]
I've amend the config and unauthorized method as suggested and added some tests

**Comment by JeffBeltran** [comment]
oh i like this thank you, question is when will this be tagged for release?

**Comment by santigarcor** [comment]
@JeffBeltran I'm working on new docs and a new feature and then i'll release it.

**Pull request merged**
