### PR TITLE
Minor refactorings, typehinting

### PR DESCRIPTION
**Pull request by GeoSot**
Typehint fixes
Some minor refactorings
`user->allPermissions()` can query scoped on teams

### CODE REVIEW

**Comment by santigarcor** [comment]
Thank you, but could you open a new one only with the teams scoping for the `allPermissions`

**Comment by GeoSot** [comment]
Excuse me, can you be more specific?
Do you want  the typehints correction in separate PR, or may I omit them?
And I proposed  some  micro changes on LaratrustUserQueryChecker , and LaratrustHasScopes.
What would you like to do with them?

**Comment by santigarcor** [comment]
I refer to the `allPermissions` addition. Regarding the other changes, you can omit them because I'm thinking on version 7.x so I'll try to refactor, clean or drop some parts of the code like the different checkers I think i'll drop the query checker and only use the default one to simplify things.

**Comment by GeoSot** [comment]
Oh... Ok. nice to know about that

**Pull request closed without merging**
